name: github-actions-test

on:
  push:
    branches:
      - main

jobs:
  script-runner:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives permission to push changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run python script
        run: |
          python logs.py

      - name: Save logs
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add logs.txt
          git commit -m "Update logs" || echo "No changes"
          git push || echo "Push failed"